# Permalinks
permalink:           pretty

# Setup
exclude:             [Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               'Teaching on Testbeds'
tagline:             ''
description:         'Experiential learning materials for computer networks, network security, cloud computing, and related topics.'
url:                 'https://teaching-on-testbeds.github.io'
baseurl:             ''

# About/contact
author:
  name:              'Fraida Fund'
  url:               'https://engineering.nyu.edu/faculty/fraida-fund'
  email:             'ffund@nyu.edu'

# Custom vars
version:             1.1.0

collections:
  posts:
    output: true
    permalink: /blog/:title
